### ISSUE TITLE
Error in installation package incompatible with filament v3

### ISSUE THREAD

**Issue by PLGUPICTO** [TappNetwork/filament-survey#3]
I got this error with the filament v3.0.15 with fresh install.

I also try installing separately "matt-daneshvar/laravel-survey": "^0.3.0". with same results.

Problem 1
    - Root composer.json requires tapp/filament-survey 3.0 -> satisfiable by tapp/filament-survey[v3.0.0].
    - tapp/filament-survey v3.0.0 requires matt-daneshvar/laravel-survey dev-translatable -> found matt-daneshvar/laravel-survey[dev-master, dev-analysis-YOmbdj, v0.1.0, ..., v0.3.0] but it does not match the constraint.

**Comment by andreia** [comment]
Thanks for reporting this so quickly! :)

I was testing it and I don't think it's possible to require this modified version of Laravel Survey directly from the plugin, so I removed it from plugin's `composer.json` file and updated the installation instructions on README. 

Please let me know if the installation steps on README work for you.
