### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by gtresnandika** [TappNetwork/filament-survey#7]
im new in filament, especially on V3, how to use it? can you give documentation about how to use it on filament? thx

**Comment by wrtisans** [comment]
as i understand, this is only for the creation process and doesn't offer a view for the customer (end user)... if i misunderstood please let me know

**Comment by johnwesely** [comment]
We are working a new package right now Tapp/filament-form-builder which should be released within a week that offers a view for completed surveys and uses filament form components instead of the bootstrap styled ones from laravel-survey.
