### ISSUE TITLE
Route [filament.admin.resources.surveys.create-question] not defined.

### ISSUE THREAD

**Issue by danhvu02** [TappNetwork/filament-survey#9]
In survey resource class,  I got error saying the route not defined.

                Action::make('CreateQuestion')
                    ->url(fn (Survey $record): string => route('filament.admin.resources.surveys.create-question', $record->id))
                    ->color('success'),
            ], position: ActionsPosition::BeforeColumns)

**Comment by johnwesely** [comment]
@danhvu02 Apologies for the delay, on this, but we have since pushed a new version that resolves this issue and greatly streamlines the survey creation process.
